### ISSUE TITLE
Test case for version 0.7

### ISSUE THREAD

**Issue by mmaelicke** [VForWaTer/tool_vforwater_loader#1]
@MarcusStrobl @elnazazmi @AlexDo1 @joergmeyer-kit 
Mentioning all of you for reference

With the version `v0.4.0` of the image, we have the first step of loading and slicing the data files in place. Clipping and harmonization are still missing.
Right now, the netCDF seem to behave...

For running locally you can use the `docker-compose.yml`, which also hints on how to run the container.
The docker compose spins up a clean database which needs to be populated first. You can use the vforwater/scripts repository. I used the lysimeter example (Fendt-1) and the hyras example on the hyras branch to populate the database.

To decrease the file sizes, I downloaded only 3 hyras files from here:
https://opendata.dwd.de/climate_environment/CDC/grids_germany/daily/hyras_de/precipitation/

the 2012, 2013, 2014 files in the `v5` version ie: [here](https://opendata.dwd.de/climate_environment/CDC/grids_germany/daily/hyras_de/precipitation/pr_hyras_1_2013_v5-0_de.nc)

then the hyras upload script only uses these three as a resource.

The scripts repo is not yet suited very well for reproduction, but we are on it.

With docker compose up, you can start the tool itself with 
```
docker compose run --rm loader
```

I will post issues/examples including files, as soon as I have specific questions.

**Comment by mmaelicke** [comment]
CI just build the container here: https://github.com/VForWaTer/tool_vforwater_loader/pkgs/container/tbr_vforwater_loader

**Comment by mmaelicke** [comment]
@AlexDo1, @MarcusStrobl, @elnazazmi  just released version `0.7.0`.

This version includes a (hopefully) fully reproducible [example for HYRAS data](https://github.com/VForWaTer/tool_vforwater_loader/tree/main/examples/hyras).

**Comment by elnazazmi** [comment]
I could get the expected results with this minor error:

[2024-02-19 14:45:38,637] - [ERROR] - [ERRORED on loading file </out/datasets/precipitation_1/precipitation_1_part_4.nc>]
Traceback (most recent call last):
  File "/src/ingestor.py", line 187, in load_files
    table_name = _switch_source_loader(entry, fname)
  File "/src/ingestor.py", line 232, in _switch_source_loader
    return load_xarray_to_duckdb(entry, ds)
  File "/src/ingestor.py", line 276, in load_xarray_to_duckdb
    db.execute(sql)
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'

**Comment by elnazazmi** [comment]
It works now with the new version of the loader.
